Update CI to the latest versions

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -1,71 +1,60 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches:
-      - main
-      - master
+    branches: [main, master]
   pull_request:
-    branches:
-      - main
-      - master
+    branches: [main, master]
 
 name: test-coverage
 
 jobs:
   test-coverage:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     env:
-      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
-      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
 
-      - uses: r-lib/actions/setup-r@v1
-
-      - uses: r-lib/actions/setup-pandoc@v1
-
-      - uses: r-lib/actions/setup-tinytex@v1
-
-      - name: Install packages from cran (source)
-        run: |
-          install.packages('remotes')
-          install.packages('pkgbuild')
-          install.packages("jsonlite", type="source")
-          install.packages("usethis", type="source")
-          install.packages("symengine", type="source")
-          remotes::install_cran("covr")
-        shell: Rscript {0}
-
-      - name: Query dependencies
-        run: |
-          install.packages('remotes')
-          remotes::install_github("nlmixr2/dparser-R")
-          remotes::install_cran("stringi")
-          remotes::install_github("https://github.com/symengine/symengine.R")
-          remotes::install_github("nlmixr2/nlmixr2data")
-          remotes::install_github("nlmixr2/lotri")
-          remotes::install_github("nlmixr2/rxode2ll")
-          remotes::install_github("nlmixr2/rxode2parse")
-          remotes::install_github("nlmixr2/rxode2")
-          remotes::install_github("nlmixr2/nlmixr2est")
-          remotes::install_github("nlmixr2/nlmixr2extra")
-          remotes::install_github("nlmixr2/nlmixr2plot")
-        shell: Rscript {0}
-
-      - name: Cache R packages
-        uses: actions/cache@v2
+      - uses: r-lib/actions/setup-r@v2
         with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
-          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
+          use-public-rspm: true
 
-      - name: Install dependencies
-        run: |
-          remotes::install_deps(dependencies = TRUE)
-        shell: Rscript {0}
+      - uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          extra-packages: |
+            any::covr
+            nlmixr2/lotri
+            nlmixr2/rxode2ll
+            nlmixr2/rxode2parse
+            nlmixr2/rxode2random
+            nlmixr2/rxode2et
+            nlmixr2/rxode2
+            nlmixr2/nlmixr2est
+            nlmixr2/nlmixr2extra
+            nlmixr2/nlmixr2plot
+          needs: coverage
 
       - name: Test coverage
         run: |
-           options(covr.flags = c(CFLAGS = "-O0 --coverage", CXXFLAGS = "-O0 --coverage -prof-gen=srcpos", LDFLAGS = "--coverage"))
-           pkgbuild::with_build_tools(covr::codecov(quiet=FALSE))
+          covr::codecov(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
+          )
         shell: Rscript {0}
+
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
